services:
  auth-db:
    image: 'postgres:latest'
    ports:
      - "15432:5432"
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  auth-service:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - postgres-network
    env_file:
      - .env
    environment:
      POSTGRES_URL: jdbc:postgresql://auth-db:5432/postgres
    depends_on:
      - auth-db

networks:
  postgres-network:
    driver: bridge